# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'
repo = 'altercation/vim-colors-solarized'
repo = 'Shougo/Unite.vim'
repo = 'Shougo/unite-outline'
repo = 'thinca/vim-quickrun'
repo = 'kana/vim-smartinput'
repo = 'kana/vim-textobj-user'
repo = 'Shougo/neocomplete.vim'
repo = 'davidhalter/jedi-vim'
repo = 'andviro/flake8-vim'
repo = 'hynek/vim-python-pep8-indent'
repo = 'tpope/vim-markdown'
repo = 'scrooloose/syntastic'
repo = 'airblade/vim-gitgutter'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']


# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

